name: manage-azure-policy-b034b4eb
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policy/initiatives/Public_network_access_should_be_disabled_for_PaaS_services_Deny-PublicPaaSEndpoints/**'
#      - 'policy/initiatives/Deploy_Microsoft_Defender_for_Cloud_configuration_Deploy-ASCDF-Config/**'
#      - 'policy/initiatives/Deploy_Diagnostic_Settings_to_Azure_Services_Deploy-Diagnostics-LogAnalytics/**'
#      - 'policy/initiatives/Configure_Azure_PaaS_services_to_use_private_DNS_zones_Deploy-Private-DNS-Zones/**'
#      - 'policy/initiatives/Deploy_SQL_Database_built-in_SQL_security_configuration_Deploy-Sql-Security/**'
#      - 'policy/initiatives/Deny_or_Deploy_and_append_TLS_requirements_and_SSL_enforcement_on_resources_without_Encryption_in_transit_Enforce-EncryptTransit/**'
#      - 'policy/initiatives/Deny_or_Audit_resources_without_Encryption_with_a_customer-managed_key_(CMK)_Enforce-Encryption-CMK/**'
#      - .github/workflows/manage-azure-policy-b034b4eb.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_b034b4eb}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policy/initiatives/Public_network_access_should_be_disabled_for_PaaS_services_Deny-PublicPaaSEndpoints/**
          policy/initiatives/Deploy_Microsoft_Defender_for_Cloud_configuration_Deploy-ASCDF-Config/**
          policy/initiatives/Deploy_Diagnostic_Settings_to_Azure_Services_Deploy-Diagnostics-LogAnalytics/**
          policy/initiatives/Configure_Azure_PaaS_services_to_use_private_DNS_zones_Deploy-Private-DNS-Zones/**
          policy/initiatives/Deploy_SQL_Database_built-in_SQL_security_configuration_Deploy-Sql-Security/**
          policy/initiatives/Deny_or_Deploy_and_append_TLS_requirements_and_SSL_enforcement_on_resources_without_Encryption_in_transit_Enforce-EncryptTransit/**
          policy/initiatives/Deny_or_Audit_resources_without_Encryption_with_a_customer-managed_key_(CMK)_Enforce-Encryption-CMK/**
